/**
 * The shape of the horizontal Kuponi wordmark, stated once.
 *
 * `assets/branding/kuponi-wordmark/color-horizontal.png` is 1200x240 — exactly
 * 5:1 — and `brandMark.test.ts` reads the PNG header on every run, so this
 * number cannot quietly go stale. It has to be stated somewhere: the assets are
 * generated by `scripts/build-kuponi-wordmarks.py`, and a re-export that
 * changed the canvas would otherwise leave five screens sizing the mark from a
 * ratio that no longer exists.
 */
export const WORDMARK_ASPECT = 1200 / 240;

/**
 * A box the shape of the artwork, so `contain` has nothing to letterbox.
 *
 * The height has to be stated, not left to `aspectRatio`: React Native Web
 * pins the asset's intrinsic height inline on the Image wrapper, and CSS drops
 * `aspect-ratio` once width and height are both definite. So the ratio gets
 * applied here, in one place, rather than hand-multiplied per screen — which
 * is how four of the five call sites came to disagree about the same image.
 */
export function wordmarkBox(width: number): { width: number; height: number } {
  return { width, height: width / WORDMARK_ASPECT };
}
