/**
 * Static logo assets, bundled by Metro.
 *
 * The web build serves these from /legacy-images, but native has no such URL,
 * so every file is required literally here (Metro cannot resolve a computed
 * require). Generated from public/legacy-images; non-image files are skipped.
 */
const logoAssets: Record<string, number> = {
  "BuyMe.png": require("../../public/legacy-images/BuyMe.png"),
  "Hamalabiya.png": require("../../public/legacy-images/Hamalabiya.png"),
  "Laline.png": require("../../public/legacy-images/Laline.png"),
  "McDonalds.png": require("../../public/legacy-images/McDonalds.png"),
  "Wolt.png": require("../../public/legacy-images/Wolt.png"),
  "airalo.png": require("../../public/legacy-images/airalo.png"),
  "alm.jpg": require("../../public/legacy-images/alm.jpg"),
  "arcaffe.png": require("../../public/legacy-images/arcaffe.png"),
  "arkia.png": require("../../public/legacy-images/arkia.png"),
  "be_shufersal.png": require("../../public/legacy-images/be_shufersal.png"),
  "ben_and_jerrys.png": require("../../public/legacy-images/ben_and_jerrys.png"),
  "benedict.jpeg": require("../../public/legacy-images/benedict.jpeg"),
  "burger_king.png": require("../../public/legacy-images/burger_king.png"),
  "burger_ranch.png": require("../../public/legacy-images/burger_ranch.png"),
  "cafe_cafe.png": require("../../public/legacy-images/cafe_cafe.png"),
  "carrefour.png": require("../../public/legacy-images/carrefour.png"),
  "cinema_city.png": require("../../public/legacy-images/cinema_city.png"),
  "cinematheque_tlv..png": require("../../public/legacy-images/cinematheque_tlv..png"),
  "default.png": require("../../public/legacy-images/default.png"),
  "default_logo.png": require("../../public/legacy-images/default_logo.png"),
  "dominos_pizza.png": require("../../public/legacy-images/dominos_pizza.png"),
  "dream_card.jpg": require("../../public/legacy-images/dream_card.jpg"),
  "elite_coffee.png": require("../../public/legacy-images/elite_coffee.png"),
  "fox_home.png": require("../../public/legacy-images/fox_home.png"),
  "freefit.png": require("../../public/legacy-images/freefit.png"),
  "golda.png": require("../../public/legacy-images/golda.png"),
  "goodpharm.png": require("../../public/legacy-images/goodpharm.png"),
  "google-logo.png": require("../../public/legacy-images/google-logo.png"),
  "hot_cinema.jpg": require("../../public/legacy-images/hot_cinema.jpg"),
  "itay_brands.png": require("../../public/legacy-images/itay_brands.png"),
  "kfc.png": require("../../public/legacy-images/kfc.png"),
  "la_shuk.png": require("../../public/legacy-images/la_shuk.png"),
  "lagenda.png": require("../../public/legacy-images/lagenda.png"),
  "logo.png": require("../../public/legacy-images/logo.png"),
  "logo_old.png": require("../../public/legacy-images/logo_old.png"),
  "love_gift_card.png": require("../../public/legacy-images/love_gift_card.png"),
  "maafe_naaman.png": require("../../public/legacy-images/maafe_naaman.png"),
  "mega_sport.jpg": require("../../public/legacy-images/mega_sport.jpg"),
  "miki_shemo.png": require("../../public/legacy-images/miki_shemo.png"),
  "mishloha.jpeg": require("../../public/legacy-images/mishloha.jpeg"),
  "movieland.png": require("../../public/legacy-images/movieland.png"),
  "nitzan_haduvdevan.jpg": require("../../public/legacy-images/nitzan_haduvdevan.jpg"),
  "nofshonit_plus.png": require("../../public/legacy-images/nofshonit_plus.png"),
  "office_depot_70.png": require("../../public/legacy-images/office_depot_70.png"),
  "pais.png": require("../../public/legacy-images/pais.png"),
  "pandora.jpg": require("../../public/legacy-images/pandora.jpg"),
  "papa_johns.png": require("../../public/legacy-images/papa_johns.png"),
  "peloton.jpeg": require("../../public/legacy-images/peloton.jpeg"),
  "pizza_hut.png": require("../../public/legacy-images/pizza_hut.png"),
  "polgat.png": require("../../public/legacy-images/polgat.png"),
  "power_gift.jpeg": require("../../public/legacy-images/power_gift.jpeg"),
  "rami_levi.jpg": require("../../public/legacy-images/rami_levi.jpg"),
  "rav_chen.png": require("../../public/legacy-images/rav_chen.png"),
  "rebar.png": require("../../public/legacy-images/rebar.png"),
  "restaurants_coupon.jpg": require("../../public/legacy-images/restaurants_coupon.jpg"),
  "roladin.png": require("../../public/legacy-images/roladin.png"),
  "soho.png": require("../../public/legacy-images/soho.png"),
  "tav_plus.png": require("../../public/legacy-images/tav_plus.png"),
  "telegram_bot.png": require("../../public/legacy-images/telegram_bot.png"),
  "together_for_you.png": require("../../public/legacy-images/together_for_you.png"),
  "vans.jpeg": require("../../public/legacy-images/vans.jpeg"),
  "victory.jpg": require("../../public/legacy-images/victory.jpg"),
  "xtra.png": require("../../public/legacy-images/xtra.png"),
  "yes_planet.jpg": require("../../public/legacy-images/yes_planet.jpg"),
  "\u05de\u05d7\u05e1\u05e0\u05d9_\u05d7\u05e9\u05de\u05dc_68_manual.png": require("../../public/legacy-images/מחסני_חשמל_68_manual.png"),
  "\u05de\u05e9\u05dc\u05d5\u05d7\u05d4_64_manual.jpeg": require("../../public/legacy-images/משלוחה_64_manual.jpeg"),
};

export function getLogoAsset(fileName: string): number | undefined {
  return logoAssets[fileName];
}
