version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "react-native"
        versions: [">=0.87.0"]
      - dependency-name: "react-native-worklets"
        versions: [">=0.11.0"]
