/// <reference types="expo/types" />

// Pulls in Expo's ambient types (asset modules, `process.env.EXPO_PUBLIC_*`, ...).
// Regenerated by the Expo CLI; kept in version control so a fresh clone type-checks
// before the dev server has been started.
