plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.itaykarkason.couponmaster.widget'
version = '1.0.0'

android {
  namespace "com.itaykarkason.couponmaster.widget"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'
}
