create table if not exists public.coupon_usage_imports (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  import_key text not null,
  coupon_id integer not null references public.coupon(id) on delete cascade,
  usage_count integer not null,
  total_amount double precision not null,
  created_at timestamptz not null default now(),
  unique (user_id, import_key)
);

alter table public.coupon_usage_imports enable row level security;
revoke all on public.coupon_usage_imports from anon, authenticated;

create or replace function public.record_coupon_usage_batch(
  p_coupon_id integer,
  p_usages jsonb,
  p_import_key text
)
returns table (new_used double precision, fully_used boolean, inserted_count integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user integer;
  v_value double precision;
  v_used double precision;
  v_total double precision;
  v_count integer;
  v_existing public.coupon_usage_imports%rowtype;
begin
  v_user := public.app_user_id();
  if v_user is null then raise exception 'NOT_AUTHENTICATED' using errcode = '28000'; end if;
  if p_import_key is null or length(btrim(p_import_key)) < 8 then
    raise exception 'INVALID_IMPORT_KEY' using errcode = '22023';
  end if;

  select * into v_existing from public.coupon_usage_imports
  where user_id = v_user and import_key = p_import_key;
  if found then
    select coalesce(c.used_value, 0), c.value into v_used, v_value from public.coupon c where c.id = v_existing.coupon_id;
    return query select v_used, v_used >= v_value, v_existing.usage_count;
    return;
  end if;

  if jsonb_typeof(p_usages) <> 'array' or jsonb_array_length(p_usages) = 0 or jsonb_array_length(p_usages) > 50 then
    raise exception 'INVALID_USAGES' using errcode = '22023';
  end if;

  select c.value, coalesce(c.used_value, 0) into v_value, v_used
  from public.coupon c
  where c.id = p_coupon_id and c.user_id = v_user
  for update;
  if not found then raise exception 'COUPON_NOT_FOUND' using errcode = '42501'; end if;

  select count(*), sum(x.amount) into v_count, v_total
  from jsonb_to_recordset(p_usages) as x(amount double precision);
  if v_count = 0 or v_total is null or v_total <= 0 or exists (
    select 1 from jsonb_to_recordset(p_usages) as x(amount double precision)
    where x.amount is null or x.amount <= 0 or x.amount = 'NaN'::double precision
  ) then raise exception 'INVALID_AMOUNT' using errcode = '22023'; end if;
  if v_used + v_total > v_value then raise exception 'INSUFFICIENT_BALANCE' using errcode = '22023'; end if;

  insert into public.coupon_usage (
    coupon_id, used_amount, action, details, place_name, place_address, latitude, longitude, timestamp
  )
  select p_coupon_id, x.amount, 'usage', nullif(btrim(coalesce(x.details, '')), ''),
    nullif(btrim(coalesce(x.place_name, '')), ''), nullif(btrim(coalesce(x.place_address, '')), ''),
    x.latitude, x.longitude,
    coalesce(nullif(x.used_at, '')::timestamptz at time zone 'utc', now() at time zone 'utc')
  from jsonb_to_recordset(p_usages) as x(
    amount double precision, details text, place_name text, place_address text,
    latitude double precision, longitude double precision, used_at text
  );

  v_used := v_used + v_total;
  update public.coupon set used_value = v_used,
    status = case when v_used >= v_value then 'נוצל' else 'פעיל' end
  where id = p_coupon_id;

  insert into public.coupon_usage_imports(user_id, import_key, coupon_id, usage_count, total_amount)
  values (v_user, p_import_key, p_coupon_id, v_count, v_total);

  return query select v_used, v_used >= v_value, v_count;
end;
$$;

revoke execute on function public.record_coupon_usage_batch(integer, jsonb, text) from public, anon;
grant execute on function public.record_coupon_usage_batch(integer, jsonb, text) to authenticated;
