create table if not exists public.coupon_places (
  id bigint generated by default as identity primary key,
  normalized_name text not null unique,
  place_name text not null,
  place_address text,
  latitude double precision,
  longitude double precision,
  google_place_id text,
  source text not null default 'google_places',
  last_verified_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint coupon_places_latitude_check check (latitude is null or latitude between -90 and 90),
  constraint coupon_places_longitude_check check (longitude is null or longitude between -180 and 180)
);

create index if not exists coupon_places_name_search_idx
  on public.coupon_places using gin (to_tsvector('simple', place_name || ' ' || coalesce(place_address, '')));

alter table public.coupon_places enable row level security;

drop policy if exists coupon_places_authenticated_read on public.coupon_places;
create policy coupon_places_authenticated_read on public.coupon_places for select to authenticated using (true);
drop policy if exists coupon_places_authenticated_write on public.coupon_places;
create policy coupon_places_authenticated_write on public.coupon_places for insert to authenticated with check (true);
drop policy if exists coupon_places_authenticated_update on public.coupon_places;
create policy coupon_places_authenticated_update on public.coupon_places for update to authenticated using (true) with check (true);

insert into public.coupon_places (normalized_name, place_name, place_address, source)
values ('גוד פארם כיכר רבין', 'גוד פארם כיכר רבין', 'רחוב בלוך 2, תל אביב', 'verified_web_search')
on conflict (normalized_name) do update set place_address = excluded.place_address, updated_at = now();
