-- Coupon sales live outside the coupon row. The coupon keeps only the link to
-- its latest sale, while this immutable snapshot preserves the seller's ledger
-- after ownership moves to another user.
create table if not exists public.coupon_sales (
  id bigint generated by default as identity primary key,
  coupon_id integer references public.coupon(id) on delete set null,
  seller_user_id integer not null references public.users(id) on delete cascade,
  buyer_user_id integer references public.users(id) on delete set null,
  share_id integer references public.coupon_shares(id) on delete set null,
  sale_type text not null check (sale_type in ('manual', 'transfer')),
  status text not null default 'pending' check (status in ('pending', 'completed', 'declined', 'cancelled')),
  buyer_first_name text not null,
  buyer_last_name text not null,
  buyer_phone text not null,
  buyer_email text,
  sale_price double precision not null check (sale_price >= 0 and sale_price <> 'NaN'::double precision),
  coupon_value_snapshot double precision not null check (coupon_value_snapshot >= 0),
  coupon_cost_snapshot double precision not null check (coupon_cost_snapshot >= 0),
  coupon_used_value_snapshot double precision not null default 0 check (coupon_used_value_snapshot >= 0),
  company_snapshot text not null,
  description_snapshot text,
  expiration_snapshot date,
  sold_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint coupon_sales_buyer_email_format check (buyer_email is null or buyer_email ~* '^\S+@\S+\.\S+$')
);

alter table public.coupon add column if not exists sale_id bigint;
alter table public.coupon drop constraint if exists coupon_sale_id_fkey;
alter table public.coupon add constraint coupon_sale_id_fkey
  foreign key (sale_id) references public.coupon_sales(id) on delete set null;
alter table public.coupon_shares add column if not exists sale_id bigint references public.coupon_sales(id) on delete set null;

create unique index if not exists coupon_sales_one_open_sale_per_coupon
  on public.coupon_sales(coupon_id) where status in ('pending', 'completed');
create index if not exists coupon_sales_seller_created_idx
  on public.coupon_sales(seller_user_id, created_at desc);

alter table public.coupon_sales enable row level security;
create policy coupon_sales_seller_select on public.coupon_sales
  for select to authenticated using (seller_user_id = public.app_user_id());
revoke insert, update, delete on public.coupon_sales from anon, authenticated;
grant select on public.coupon_sales to authenticated;

create or replace function public.record_manual_coupon_sale(
  p_coupon_id integer, p_sale_price double precision,
  p_buyer_first_name text, p_buyer_last_name text, p_buyer_phone text,
  p_buyer_email text default null, p_sold_at timestamptz default now()
)
returns bigint language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user integer; v_coupon public.coupon%rowtype; v_sale_id bigint;
begin
  v_user := public.app_user_id();
  if v_user is null then raise exception 'NOT_AUTHENTICATED' using errcode = '28000'; end if;
  if p_sale_price is null or p_sale_price < 0 or p_sale_price = 'NaN'::double precision
    or nullif(btrim(p_buyer_first_name), '') is null
    or nullif(btrim(p_buyer_last_name), '') is null
    or nullif(btrim(p_buyer_phone), '') is null then
    raise exception 'INVALID_SALE_INPUT' using errcode = '22023';
  end if;
  select * into v_coupon from public.coupon
    where id = p_coupon_id and user_id = v_user and deleted_at is null for update;
  if not found or v_coupon.status = 'נמכר' then raise exception 'COUPON_NOT_FOUND' using errcode = '42501'; end if;
  insert into public.coupon_sales(
    coupon_id,seller_user_id,sale_type,status,buyer_first_name,buyer_last_name,buyer_phone,buyer_email,
    sale_price,coupon_value_snapshot,coupon_cost_snapshot,coupon_used_value_snapshot,
    company_snapshot,description_snapshot,expiration_snapshot,sold_at
  ) values (
    v_coupon.id,v_user,'manual','completed',btrim(p_buyer_first_name),btrim(p_buyer_last_name),btrim(p_buyer_phone),
    nullif(lower(btrim(coalesce(p_buyer_email,''))),''),p_sale_price,v_coupon.value,v_coupon.cost,v_coupon.used_value,
    v_coupon.company,v_coupon.description,v_coupon.expiration,p_sold_at
  ) returning id into v_sale_id;
  update public.coupon set status = 'נמכר', sale_id = v_sale_id,
    show_in_widget = false, widget_display_order = null, auto_update = false
    where id = v_coupon.id;
  update public.coupon_shares set status = 'revoked', revoked_at = now()
    where coupon_id = v_coupon.id and status in ('pending','accepted');
  return v_sale_id;
end $$;
revoke all on function public.record_manual_coupon_sale(integer,double precision,text,text,text,text,timestamptz) from public, anon;
grant execute on function public.record_manual_coupon_sale(integer,double precision,text,text,text,text,timestamptz) to authenticated;

-- Complete or reject a transfer and its optional sale in the same transaction.
create or replace function public.respond_to_coupon_share(p_share_id integer, p_accept boolean)
returns table (share_id integer, new_status text, coupon_id integer, share_type text)
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user integer; v_share public.coupon_shares%rowtype; v_sale public.coupon_sales%rowtype;
begin
  v_user := public.app_user_id();
  if v_user is null then raise exception 'NOT_AUTHENTICATED' using errcode = '28000'; end if;
  select * into v_share from public.coupon_shares where id = p_share_id for update;
  if not found or v_share.shared_with_user_id <> v_user then raise exception 'SHARE_NOT_FOUND' using errcode = '42501'; end if;
  if v_share.status <> 'pending' or v_share.share_expires_at <= now() then raise exception 'SHARE_NOT_PENDING' using errcode = '22023'; end if;
  if not p_accept then
    update public.coupon_shares set status='declined' where id=p_share_id;
    if v_share.sale_id is not null then update public.coupon_sales set status='declined',updated_at=now() where id=v_share.sale_id; end if;
    return query select v_share.id,'declined'::text,v_share.coupon_id,v_share.share_type; return;
  end if;
  perform 1 from public.coupon where id=v_share.coupon_id and user_id=v_share.shared_by_user_id for update;
  if not found then raise exception 'COUPON_NOT_FOUND' using errcode = '42501'; end if;
  if v_share.share_type='transfer' then
    update public.coupon set user_id=v_user,status=case when used_value>=value then 'נוצל' else 'פעיל' end where id=v_share.coupon_id;
    update public.coupon_shares set status='transferred',accepted_at=now() where id=p_share_id;
    if v_share.sale_id is not null then
      update public.coupon_sales set status='completed',buyer_user_id=v_user,sold_at=now(),updated_at=now() where id=v_share.sale_id;
    end if;
    update public.coupon_shares set status='revoked',revoked_at=now()
      where coupon_id=v_share.coupon_id and id<>p_share_id and status in ('pending','accepted');
    return query select v_share.id,'transferred'::text,v_share.coupon_id,v_share.share_type;
  else
    update public.coupon_shares set status='accepted',accepted_at=now() where id=p_share_id;
    return query select v_share.id,'accepted'::text,v_share.coupon_id,v_share.share_type;
  end if;
end $$;
